# yaml-language-server: $schema=https://raw.githubusercontent.com/aquaproj/aqua/main/json-schema/registry.json
packages:
  - type: github_release
    repo_owner: helmfile
    repo_name: helmfile
    aliases:
      - name: roboll/helmfile
    asset: helmfile_{{trimV .Version}}_{{.OS}}_{{.Arch}}.tar.gz
    description: Declaratively deploy your Kubernetes manifests, Kustomize configs, and Charts as Helm releases in one shot
    checksum:
      type: github_release
      asset: helmfile_{{trimV .Version}}_checksums.txt
      algorithm: sha256
    version_constraint: semver(">= 0.145.0")
    version_overrides:
      - version_constraint: "true"
        repo_owner: roboll
        rosetta2: true
        asset: helmfile_{{.OS}}_{{.Arch}}
        format: raw
        supported_envs:
          - darwin
          - linux
          - amd64
        checksum:
          enabled: false
