# yaml-language-server: $schema=https://raw.githubusercontent.com/aquaproj/aqua/main/json-schema/registry.json
packages:
  - type: github_release
    repo_owner: kubernetes
    repo_name: apiextensions-apiserver
    description: API server for API extensions like CustomResourceDefinitions
    version_filter: not (Version matches "-(alpha|beta|rc)")
    version_constraint: "false"
    version_overrides:
      - version_constraint: "true"
        no_asset: true
