---
# the configuration file of cmdx - task runner
# https://github.com/suzuki-shunsuke/cmdx
tasks:
  - name: install
    short: i
    description: install all packages
    usage: install all packages
    script: aqua -c aqua-all.yaml i --test
  - name: test
    short: t
    description: test
    usage: test
    script: aqua i --test
  - name: exec
    short: x
    description: exec with aqua-all.yaml
    usage: exec with aqua-all.yaml
    script: AQUA_CONFIG=aqua-all.yaml aqua exec -- {{._builtin.args_string}}
  - name: which
    short: w
    description: aqua which with aqua-all.yaml
    usage: aqua which with aqua-all.yaml
    script: "AQUA_CONFIG=aqua-all.yaml aqua which {{.package}}"
    args:
      - name: package
        required: true
  - name: generate
    short: g
    description: aqua generate with aqua-all.yaml
    usage: aqua generate with aqua-all.yaml
    script: aqua -c aqua-all.yaml g
  - name: release
    short: r
    description: release the new version
    usage: release the new version
    script: |
      git tag -m "chore: release {{.version}}" "{{.version}}"
      git push origin "{{.version}}"
    args:
      - name: version
        required: true
        validate:
          - regexp: "^v\\d+\\.\\d+.\\d+(-\\d+)?$"
  - name: gr
    description: aqua-registry gr
    usage: aqua-registry gr
    script: aqua-registry gr
  - name: new
    description: aqua-registry create-pr-new-pkg
    usage: aqua-registry create-pr-new-pkg
    script: aqua-registry create-pr-new-pkg "{{.package}}"
    args:
      - name: package
        required: true
  - name: sd
    description: aqua-registry scaffold --deep
    usage: aqua-registry scaffold --deep
    script: aqua-registry scaffold --deep "{{.package}}"
    args:
      - name: package
        required: true
  - name: s
    description: aqua-registry scaffold
    usage: aqua-registry scaffold
    script: aqua-registry scaffold "{{.package}}"
    args:
      - name: package
        required: true
