---
# the configuration file of cmdx - task runner
# https://github.com/suzuki-shunsuke/cmdx
tasks:
  - name: install
    short: i
    description: install all packages
    usage: install all packages
    script: clivm -c clivm-all.yaml i --test
  - name: test
    short: t
    description: test
    usage: test
    script: clivm i --test
  - name: exec
    short: x
    description: exec with clivm-all.yaml
    usage: exec with clivm-all.yaml
    script: AQUA_CONFIG=clivm-all.yaml clivm exec -- {{._builtin.args_string}}
  - name: which
    short: w
    description: clivm which with clivm-all.yaml
    usage: clivm which with clivm-all.yaml
    script: "AQUA_CONFIG=clivm-all.yaml clivm which {{.package}}"
    args:
      - name: package
        required: true
  - name: generate
    short: g
    description: clivm generate with clivm-all.yaml
    usage: clivm generate with clivm-all.yaml
    script: clivm -c clivm-all.yaml g
  - name: release
    short: r
    description: release the new version
    usage: release the new version
    script: |
      git tag "{{.version}}"
      git push origin "{{.version}}"
    args:
      - name: version
        required: true
        validate:
          - regexp: "^v\\d+\\.\\d+.\\d+(-\\d+)?$"
  - name: registry
    description: Merge registry.yaml
    usage: Merge registry.yaml
    script: bash generate-registry.sh
