packages:
  - name: grafana/mimir/mimir
    type: github_release
    repo_owner: grafana
    repo_name: mimir
    description: Grafana Mimir provides horizontally scalable, highly available, multi-tenant, long-term storage for Prometheus
    asset: mimir-{{.OS}}-{{.Arch}}
    format: raw
    version_prefix: mimir-
    supported_envs:
      - linux
      - darwin
