packages:
  - type: github_release
    repo_owner: docker
    repo_name: compose
    asset: docker-compose-{{.OS}}-{{.Arch}}
    format: raw
    description: Define and run multi-container applications with Docker
    files:
      - name: docker-cli-plugin-docker-compose
    replacements:
      amd64: x86_64
      arm64: aarch64
    version_constraint: semver(">= 2.10.1")
    checksum:
      type: github_release
      asset: checksums.txt
      algorithm: sha256
    version_overrides:
      - version_constraint: semver(">= 2.10.0")
        checksum:
          type: github_release
          asset: checksums.txt
          algorithm: sha256
      - version_constraint: "true"
