packages:
  - type: github_release
    repo_owner: docker
    repo_name: compose
    asset: docker-compose-{{.OS}}-{{.Arch}}
    format: raw
    description: Define and run multi-container applications with Docker
    files:
      - name: docker-cli-plugin-docker-compose
    replacements:
      amd64: x86_64
      arm64: aarch64
    supported_envs:
      - darwin
      - linux
      - amd64
    checksum:
      type: github_release
      path: checksums.txt
      file_format: regexp
      pattern:
        checksum: ^(.{64})
        file: "^.{64}\\s+(\\S*)$"
