packages:
  - type: github_release
    repo_owner: helm
    repo_name: chart-releaser
    asset: chart-releaser_{{trimV .Version}}_{{.OS}}_{{.Arch}}.{{.Format}}
    description: Hosting Helm Charts via GitHub Pages and Releases
    format: tar.gz
    overrides:
      - goos: windows
        format: zip
    files:
      - name: cr
    checksum:
      type: github_release
      path: checksums.txt
      file_format: regexp
      pattern:
        checksum: ^(.{64})
        file: "^.{64}\\s+(\\S*)$"
