# yaml-language-server: $schema=https://raw.githubusercontent.com/aquaproj/aqua/main/json-schema/registry.json
packages:
  - name: grafana/mimir/mimirtool
    type: github_release
    repo_owner: grafana
    repo_name: mimir
    description: Grafana Mimir provides horizontally scalable, highly available, multi-tenant, long-term storage for Prometheus
    asset: mimirtool-{{.OS}}-{{.Arch}}
    format: raw
    version_prefix: mimir-
    version_constraint: "false"
    version_overrides:
      # mimirtool Windows assets are missing only in these releases
      - version_constraint: Version in ["mimir-3.1.0-rc.0", "mimir-3.1.0", "mimir-3.1.1", "mimir-3.1.2"]
        supported_envs:
          - linux
          - darwin
      - version_constraint: "true"
        supported_envs:
          - linux
          - darwin
          - windows
