packages:
  - name: grafana/mimir/mimirtool
    type: github_release
    repo_owner: grafana
    repo_name: mimir
    description: Grafana Mimir provides horizontally scalable, highly available, multi-tenant, long-term storage for Prometheus
    asset: mimirtool-{{.OS}}-{{.Arch}}
    format: raw
    version_prefix: mimir-
    complete_windows_ext: false
    version_constraint: semver(">= 2.2.0-rc.1")
    version_overrides:
      - version_constraint: semver(">= 2.2.0-rc.0")
        supported_envs:
          - linux
          - darwin
      - version_constraint: semver("< 2.2.0-rc.0")
