# yaml-language-server: $schema=https://raw.githubusercontent.com/aquaproj/aqua/main/json-schema/registry.json
packages:
  - name: grafana/mimir/mimirtool
    type: github_release
    repo_owner: grafana
    repo_name: mimir
    description: Grafana Mimir provides horizontally scalable, highly available, multi-tenant, long-term storage for Prometheus
    version_prefix: mimir-
    version_constraint: "false"
    version_overrides:
      - version_constraint: Version == "mimir-3.2.0-rc.0"
        no_asset: true
      - version_constraint: Version in ["mimir-2.2.0-rc.0", "mimir-3.1.0-rc.0"]
        asset: mimirtool-{{.OS}}-{{.Arch}}
        format: raw
        supported_envs:
          - linux
          - darwin
      - version_constraint: semver("<= 3.0.9") or Version == "mimir-3.1.0-rc.1"
        asset: mimirtool-{{.OS}}-{{.Arch}}
        format: raw
      - version_constraint: semver("<= 3.1.2")
        asset: mimirtool-{{.OS}}-{{.Arch}}
        format: raw
        supported_envs:
          - linux
          - darwin
      - version_constraint: "true"
        asset: mimirtool-{{.OS}}-{{.Arch}}
        format: raw
