packages:
  - name: kubernetes/kubectl
    type: http
    repo_owner: kubernetes
    repo_name: kubernetes
    url: https://dl.k8s.io/{{.Version}}/bin/{{.OS}}/{{.Arch}}/kubectl
    format: raw
    description: The kubectl command line tool lets you control Kubernetes clusters
    files:
      - name: kubectl
    checksum:
      type: http
      url: https://dl.k8s.io/{{.Version}}/bin/{{.OS}}/{{.Arch}}/kubectl.sha256
      algorithm: sha256
      file_format: raw
    overrides:
      - goos: windows
        checksum:
          type: http
          url: https://dl.k8s.io/{{.Version}}/bin/{{.OS}}/{{.Arch}}/kubectl.exe.sha256
          algorithm: sha256
          file_format: raw
    version_constraint: semver(">= 1.23.0")
    version_overrides:
      - version_constraint: semver(">= 1.21.0")
        rosetta2: true
        supported_envs:
          - darwin
          - linux
          - windows/amd64
      - version_constraint: "true"
        rosetta2: true
        supported_envs:
          - darwin
          - linux
          - amd64
