packages:
  - name: kubernetes/kubectl
    type: http
    repo_owner: kubernetes
    repo_name: kubernetes
    description: The kubectl command line tool lets you control Kubernetes clusters
    url: https://storage.googleapis.com/kubernetes-release/release/{{.Version}}/bin/{{.OS}}/{{.Arch}}/kubectl
    format: raw
    checksum:
      type: http
      url: https://dl.k8s.io/{{.Version}}/bin/{{.OS}}/{{.Arch}}/kubectl.sha256
      algorithm: sha256
      file_format: raw
    overrides:
      - goos: windows
        checksum:
          url: https://dl.k8s.io/{{.Version}}/bin/{{.OS}}/{{.Arch}}/kubectl.exe.sha256
