# yaml-language-server: $schema=https://raw.githubusercontent.com/aquaproj/aqua/main/json-schema/registry.json
packages:
  - type: github_release
    repo_owner: grafana
    repo_name: gcx
    description: A CLI for managing Grafana Cloud resources. Optimized for agentic usage
    version_constraint: "false"
    version_overrides:
      - version_constraint: Version == "v0.2.0"
        asset: gcx_{{.OS}}_{{.Arch}}.{{.Format}}
        format: tar.gz
        replacements:
          amd64: x86_64
          darwin: Darwin
          linux: Linux
          windows: Windows
        checksum:
          type: github_release
          asset: gcx_checksums.txt
          algorithm: sha256
        overrides:
          - goos: windows
            format: zip
      - version_constraint: "true"
        asset: gcx_{{trimV .Version}}_{{.OS}}_{{.Arch}}.{{.Format}}
        format: tar.gz
        checksum:
          type: github_release
          asset: gcx_{{trimV .Version}}_checksums.txt
          algorithm: sha256
        overrides:
          - goos: windows
            format: zip
