packages:
  - name: kubernetes/kubectl-convert
    type: http
    repo_owner: kubernetes
    repo_name: kubernetes
    description: A plugin for Kubernetes command-line tool kubectl, which allows you to convert manifests between different API versions
    url: https://dl.k8s.io/{{.Version}}/bin/{{.OS}}/{{.Arch}}/kubectl-convert
    format: raw
    files:
      - name: kubectl-convert
    checksum:
      type: http
      url: https://dl.k8s.io/{{.Version}}/bin/{{.OS}}/{{.Arch}}/kubectl-convert.sha256
      algorithm: sha256
      file_format: raw
    overrides:
      - goos: windows
        checksum:
          type: http
          url: https://dl.k8s.io/{{.Version}}/bin/{{.OS}}/{{.Arch}}/kubectl-convert.exe.sha256
          algorithm: sha256
          file_format: raw
    version_constraint: semver(">= 1.23.0")
    version_overrides:
    - version_constraint: "true"
      supported_envs:
        - darwin
        - linux
        - windows/amd64
