# yaml-language-server: $schema=https://raw.githubusercontent.com/aquaproj/aqua/main/json-schema/registry.json
packages:
  - type: github_release
    repo_owner: kubernetes
    repo_name: kube-aggregator
    description: "Aggregator for Kubernetes-style API servers: dynamic registration, discovery summarization, secure proxy"
    version_filter: not (Version matches "-(alpha|beta|rc)")
