# yaml-language-server: $schema=https://raw.githubusercontent.com/aquaproj/aqua/main/json-schema/registry.json
packages:
  - type: http
    repo_owner: GoogleContainerTools
    repo_name: skaffold
    description: Easy and Repeatable Kubernetes Development
    url: https://storage.googleapis.com/skaffold/releases/{{.Version}}/skaffold-{{.OS}}-{{.Arch}}
    checksum:
      type: http
      url: "https://storage.googleapis.com/skaffold/releases/{{.Version}}/skaffold-{{.OS}}-{{.Arch}}.sha256"
      algorithm: sha256
    overrides:
      - goos: windows
        checksum:
          type: http
          url: "https://storage.googleapis.com/skaffold/releases/{{.Version}}/skaffold-{{.OS}}-{{.Arch}}.exe.sha256"
          algorithm: sha256
    files:
      - name: skaffold
        src: skaffold-{{.OS}}-{{.Arch}}
    supported_envs:
      - darwin
      - linux
      - amd64
