# yaml-language-server: $schema=https://raw.githubusercontent.com/aquaproj/aqua/main/json-schema/registry.json
packages:
  - name: kubernetes/kubeadm
    type: http
    repo_owner: kubernetes
    repo_name: kubernetes
    description: Kubeadm is a tool built to provide best-practice "fast paths" for creating Kubernetes clusters
    url: https://dl.k8s.io/{{.Version}}/bin/{{.OS}}/{{.Arch}}/kubeadm
    format: raw
    files:
      - name: kubeadm
    checksum:
      type: http
      url: https://dl.k8s.io/{{.Version}}/bin/{{.OS}}/{{.Arch}}/kubeadm.sha256
      algorithm: sha256
    supported_envs:
      - linux
      - windows/amd64
    overrides:
      - goos: windows
        checksum:
          type: http
          url: https://dl.k8s.io/{{.Version}}/bin/{{.OS}}/{{.Arch}}/kubeadm.exe.sha256
          algorithm: sha256
