# yaml-language-server: $schema=https://raw.githubusercontent.com/aquaproj/aqua/main/json-schema/registry.json
packages:
  - type: github_release
    repo_owner: grafana
    repo_name: agento11y
    description: Actually Useful Agent Observability
    version_prefix: plugins/agento11y/v
    asset: agento11y_{{.SemVer}}_{{.OS}}_{{.Arch}}.{{.Format}}
    format: tar.gz
    checksum:
      type: github_release
      asset: agento11y_{{.SemVer}}_checksums.txt
      algorithm: sha256
    overrides:
      - goos: windows
        format: zip
