packages:
  - type: github_release
    repo_owner: roboll
    repo_name: helmfile
    description: Deploy Kubernetes Helm Charts
    asset: helmfile_{{.OS}}_{{.Arch}}
    format: raw
    supported_envs:
      - darwin
      - linux
      - amd64
    version_constraint: semver(">= 0.143.0")
    version_overrides:
      - version_constraint: semver("< 0.143.0")
        rosetta2: true
