packages:
  - type: github_release
    repo_owner: prometheus
    repo_name: alertmanager
    asset: alertmanager-{{trimV .Version}}.{{.OS}}-{{.Arch}}.tar.gz
    description: Prometheus Alertmanager
    checksum:
      type: github_release
      asset: sha256sums.txt
      file_format: regexp
      algorithm: sha256
      pattern:
        checksum: "^(\\b[A-Fa-f0-9]{64}\\b)"
        file: "^\\b[A-Fa-f0-9]{64}\\b\\s+(\\S+)$"
    files:
      - name: alertmanager
        src: alertmanager-{{trimV .Version}}.{{.OS}}-{{.Arch}}/alertmanager
      - name: amtool
        src: alertmanager-{{trimV .Version}}.{{.OS}}-{{.Arch}}/amtool
