---
name: Ask Sponsor
on:
  pull_request_target:
    types:
      - opened
jobs:
  ask_sponsor:
    uses: ./.github/workflows/wc_ask_sponsor.yaml
    permissions:
      pull-requests: write
    with:
      author: ${{github.event.pull_request.user.login}}
      pr_number: ${{github.event.pull_request.number}}
    if: |
      github.event.pull_request.user.type == 'User' &&
      github.event.pull_request.user.login != 'suzuki-shunsuke'
