---
name: autofix.ci
on: pull_request
permissions: {}
jobs:
  autofix:
    runs-on: ubuntu-24.04
    permissions: {}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false
      - run: echo "AQUA_GLOBAL_CONFIG=${AQUA_GLOBAL_CONFIG:-}:${PWD}/aqua-all.yaml" >> "$GITHUB_ENV"
      - uses: aquaproj/aqua-installer@96a9bc20066c5bf5e275b41019cfc165b25f4e2e # v4.0.5
        with:
          aqua_version: v2.61.0-0
          aqua_opts: -l -a
          policy_allow: "true"

      - name: install nllint
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
        run: nllint -v
      - name: Fix newlines
        run: git ls-files | xargs nllint -f -s

      - name: Configure NPM_CONFIG_PREFIX
        run: echo NPM_CONFIG_PREFIX="$HOME/npm-global" >> "$GITHUB_ENV"
      - run: echo "$NPM_CONFIG_PREFIX/bin" >> "$GITHUB_PATH"
      - name: Install prettier
        run: npm i -g prettier
      - name: Format code by prettier
        run: prettier -w .

      - name: install argd
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
        run: argd --version

      - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        id: changes
        with:
          list-files: shell
          filters: |
            pkgs-files:
              - added|modified: pkgs/**/pkg.yaml
              - added|modified: pkgs/**/registry.yaml

      - name: argd fix
        if: steps.changes.outputs.pkgs-files == 'true'
        run: argd fix ${{steps.changes.outputs.pkgs-files_files}}

      - name: Fix registry.yaml
        run: argd gr

      - name: install keep-sorted
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
        run: |
          keep-sorted --version
      - name: keep-sorted
        run: |
          git grep -l " keep-sorted start" | grep -v autofix.yaml | xargs keep-sorted

      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1.3.4
