---
name: prettier
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - run: npm i -g prettier
      - run: prettier -c .
