---
name: test all packages
on: workflow_dispatch

permissions: {}
env:
  AQUA_LOG_COLOR: always
jobs:
  test:
    strategy:
      matrix:
        env:
          - runs-on: windows-latest
          - runs-on: ubuntu-latest
          - runs-on: macos-latest
          - runs-on: ubuntu-latest
            goarch: arm64
          - runs-on: macos-latest
            goos: darwin
            goarch: arm64
          - runs-on: windows-latest
            goarch: arm64
    runs-on: ${{ matrix.env.runs-on }}
    defaults:
      run:
        shell: bash
    env:
      AQUA_CONFIG: aqua-all.yaml
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@32691ba7c9e7063bd457bd8f2a5703138591fa58 # v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: aquaproj/aqua-installer@928a2ee4243a9ee8312d80dc8cbaca88fb602a91 # v2.2.0
        with:
          aqua_version: v2.16.4
          aqua_opts: ""
          policy_allow: "true"
        env:
          AQUA_GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}
