---
name: Test IP restriction
on:
  pull_request: {}
  push:
    branches:
      - main
jobs:
  foo:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          persist-credentials: false
      - uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
        with:
          aqua_version: v2.43.0-1
        env:
          GITHUB_TOKEN: ${{github.token}}
      - name: Generate token
        id: token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{secrets.APP_ID}}
          private_key: ${{secrets.APP_PRIVATE_KEY}}
          repositories: >-
            ["${{github.event.repository.name}}"]
          permissions: >-
            {
              "contents": "write",
              "pull_requests": "write"
            }
      - run: aqua g bridgecrewio/checkov
      - run: aqua g bridgecrewio/checkov
        env:
          GITHUB_TOKEN: ${{github.token}}
      - run: aqua g bridgecrewio/checkov
        env:
          GITHUB_TOKEN: ${{steps.token.outputs.token}}
