---
name: test Go
on:
  push:
    branches:
      - main
    paths:
      - "**/*.go"
      - .golangci.yml
  pull_request:
    branches:
      - main
    paths:
      - "**/*.go"
      - .golangci.yml
env:
  AQUA_LOG_COLOR: always
  AQUA_CONFIG: aqua-all.yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aquaproj/aqua-installer@v1.0.0
        with:
          aqua_version: v1.17.1
      - uses: suzuki-shunsuke/github-action-golangci-lint@v0.1.3
      # - run: go test -v ./... -race -covermode=atomic
