---
name: check-files
on: workflow_call
jobs:
  check-files:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: aquaproj/registry-action/check-files@82bcd97423aaa089d22808aeca8ef94200082902 # v0.2.3
