---
name: json-schema
on: workflow_call
jobs:
  json-schema:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: aquaproj/registry-action/validate-json-schema@63f797c47a1c66ecf7a4bc4e07eb41360249190a # v0.2.4
