---
name: wc-lintnet
on: workflow_call
env:
  AQUA_LOG_COLOR: always
jobs:
  lintnet:
    runs-on: ubuntu-26.04
    env:
      AQUA_CONFIG: aqua-all.yaml
    permissions:
      contents: read
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: aquaproj/aqua-installer@82d0e83878a8657c4a6f2ff1755d3bfbfc67f329 # v4.1.0
        with:
          aqua_version: v2.64.0
          policy_allow: "true"
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}

      - run: lintnet lint
        env:
          GITHUB_TOKEN: ${{github.token}}
