---
name: wc-lintnet
on: workflow_call
env:
  AQUA_LOG_COLOR: always
jobs:
  lintnet:
    runs-on: ubuntu-latest
    env:
      AQUA_CONFIG: aqua-all.yaml
    permissions:
      contents: read
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: aquaproj/aqua-installer@96a9bc20066c5bf5e275b41019cfc165b25f4e2e # v4.0.5
        with:
          aqua_version: v2.60.2
          policy_allow: "true"
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}

      - run: lintnet lint
        env:
          GITHUB_TOKEN: ${{github.token}}
