---
name: renovate-config-validator
on: workflow_call
jobs:
  renovate-config-validator:
    uses: suzuki-shunsuke/renovate-config-validator-workflow/.github/workflows/validate.yaml@dcf025732ed76061838048f7f8b0099ae0e89876 # v0.2.5
    permissions:
      contents: read
    with:
      # https://github.com/renovatebot/renovate/discussions/35787#discussioncomment-13068531
      node-version: 22.13.1
