---
name: test-docker
on: workflow_call
jobs:
  test-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: aquaproj/aqua-installer@96a9bc20066c5bf5e275b41019cfc165b25f4e2e # v4.0.5
        with:
          aqua_version: v2.61.0-0
          policy_allow: "true"
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - name: test GitHub Release
        run: argd t suzuki-shunsuke/mkghtag
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      # # Stop testing cargo package as this step takes a long time
      # - name: test cargo package
      #   run: argd t bensadeh/tailspin
      #   env:
      #     AQUA_GITHUB_TOKEN: ${{github.token}}
