---
name: wc-test
on: workflow_call
env:
  AQUA_LOG_COLOR: always
jobs:
  list:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    env:
      AQUA_CONFIG: aqua/test.yaml
    permissions:
      contents: read
      pull-requests: read
    outputs:
      changed: ${{ steps.changed.outputs.value }}
      image: ${{ steps.image.outputs.value }}
      use_alpine: ${{ steps.alpine_required.outputs.value }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with:
          aqua_version: v2.58.0-1
          policy_allow: "true"
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}

      - name: Run ci-info and update environment variables
        run: aqua exec -- ci-info run | sed -E "s/^export //" >> "$GITHUB_ENV"
        env:
          AQUA_CONFIG: aqua/ci-info.yaml

      - name: Update aqua/test.yaml
        id: changed
        run: |
          if grep -E "target:" "$CI_INFO_TEMP_DIR/labels.txt" > /dev/null 2>&1; then
            grep -E "target:" "$CI_INFO_TEMP_DIR/labels.txt" | sed "s|^target:\(.*\)|  - import: ../pkgs/\1/pkg.yaml|" >> aqua/test.yaml
          fi
          pkgs=$(mktemp)
          grep -E "^pkgs/.*\.yaml" < "$CI_INFO_TEMP_DIR/pr_files.txt" | grep -v -E "^pkgs/crates\.io/" > "$pkgs" || :
          if [ -s "$pkgs" ]; then
            sed "s/registry\.yaml/pkg.yaml/" "$pkgs" | sort -u | sed "s|^|  - import: ../|" >> aqua/test.yaml
          fi
          echo "[INFO] aqua/test.yaml" >&2
          cat aqua/test.yaml >&2
          if git diff --quiet aqua/test.yaml; then
            echo "value=false" >> "$GITHUB_OUTPUT"
          else
            echo "value=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Check image
        id: image
        run: |
          if grep '\- import:' aqua/test.yaml | sed 's|  - import: ../\(.*\)/pkg.yaml|\1/registry.yaml|' | xargs cat | grep "type: cargo" > /dev/null 2>&1; then
            echo "value=rust:1.95.0-alpine3.23" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          if grep '\- import:' aqua/test.yaml | sed 's|  - import: ../\(.*\)/pkg.yaml|\1/registry.yaml|' | xargs cat | grep "type: go" > /dev/null 2>&1; then
            echo "value=go:1.26.2-alpine3.23" >> "$GITHUB_OUTPUT"
          fi
          echo "value=alpine:3.23.4" >> "$GITHUB_OUTPUT"

      - name: Check if alpine is required
        id: alpine_required
        run: |
          if grep '\- import:' aqua/test.yaml | sed 's|  - import: ../\(.*\)/pkg.yaml|\1/registry.yaml|' | xargs cat | grep "key: libc" > /dev/null 2>&1; then
            echo "value=true" >> "$GITHUB_OUTPUT"
          else
            echo "value=false" >> "$GITHUB_OUTPUT"
          fi

      - if: steps.changed.outputs.value == 'true'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: aqua-test.yaml
          path: aqua/test.yaml
          # We gave up using `archived: false`
          # https://github.com/cli/cli/issues/13012
          # https://github.com/actions/upload-artifact#inputs
          # archive: If 'false', only a single file can be uploaded.
          # The name of the file will be used as the artifact name (the 'name' parameter is ignored)
          # archive: false

  test:
    if: needs.list.outputs.changed == 'true'
    runs-on: ${{ matrix.env.runs-on }}
    timeout-minutes: 20
    needs: [list]
    env:
      AQUA_CONFIG: aqua/test.yaml
    permissions:
      contents: read
    strategy:
      matrix:
        env:
          - runs-on: windows-latest
            goos: ""
            goarch: ""
          - runs-on: ubuntu-24.04
            goos: ""
            goarch: ""
          - runs-on: macos-15-intel
            goos: ""
            goarch: ""
          - runs-on: ubuntu-24.04-arm
            goos: ""
            goarch: ""
          - runs-on: macos-14
            goos: ""
            goarch: ""
          - runs-on: windows-latest
            goos: ""
            goarch: arm64
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: aqua-test.yaml
          path: aqua

      - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with:
          aqua_version: v2.58.0-1
          policy_allow: "true"
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}

      - name: Install packages for testing
        run: aqua i
        env:
          AQUA_GOOS: ${{ matrix.env.goos }}
          AQUA_GOARCH: ${{ matrix.env.goarch }}
          AQUA_CONFIG: aqua/test.yaml

  test-alpine:
    if: needs.list.outputs.use_alpine == 'true'
    needs: [list]
    runs-on: ${{ matrix.env.runs-on }}
    timeout-minutes: 20
    permissions:
      contents: read
    container:
      image: mirror.gcr.io/${{needs.list.outputs.image}}
      env:
        AQUA_CONFIG: aqua/test.yaml
        AQUA_LOG_COLOR: always
    strategy:
      matrix:
        env:
          - runs-on: ubuntu-24.04
          - runs-on: ubuntu-24.04-arm
    steps:
      # Error: JavaScript Actions in Alpine containers are only supported on x64 Linux runners. Detected Linux Arm64
      # https://github.com/aquaproj/aqua-registry/actions/runs/25200221593/job/73889479345?pr=52945
      - run: apk add bash curl git github-cli
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - run: git init
      - run: git remote add origin https://github.com/aquaproj/aqua-registry
      - run: gh auth setup-git
        env:
          GH_HOST: github.com
      - run: git fetch origin --depth 1 "$GITHUB_SHA"
        env:
          GH_TOKEN: ${{github.token}}
      - run: git checkout "$GITHUB_SHA"
        env:
          GH_TOKEN: ${{github.token}}

      - run: rm aqua/test.yaml
      - run: gh run download -R "$GITHUB_REPOSITORY" "$GITHUB_RUN_ID" -n aqua-test.yaml
        working-directory: aqua
        env:
          GH_TOKEN: ${{github.token}}

      - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with:
          aqua_version: v2.58.0-1
          policy_allow: "true"
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}

      - name: Install Go
        if: |
          ! contains(needs.list.outputs.image, 'go')
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
        run: |
          aqua g -i golang/go
          aqua i -l
          go version

      - name: Install packages for testing
        run: aqua i
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
